version: "3.8"

services:
  springboot:
    build: .
    container_name: springboot_container
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_REDIS_HOST: redis_container
      SPRING_REDIS_PORT: 6378
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/backend/build/libs:/app
    command: [ "java", "-jar", "/app/Backend-0.0.1-SNAPSHOT.jar" ]
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
