services:
  springboot:
    build: .
    container_name: springboot_container
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://${PROD_DB_HOST}:${DB_PORT}/${PROD_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${PROD_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PROD_DB_PASSWORD}
      SPRING_REDIS_HOST: redis_container
      SPRING_REDIS_PORT: 6378
      SPRING_REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
#      - /home/ubuntu/backend/build/libs/Backend-0.0.1-SNAPSHOT.jar:/app/app.jar
      - /home/ubuntu/backend/src/main/resources/application.yml:/app/application.yml
      - /home/ubuntu/backend/src/main/resources/application-prod.yml:/app/application-prod.yml
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
