spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: I-Contact

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:i_contact_local}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT:27017}
      database:  ${MONGO_DATABASE}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      authentication-database: admin

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 1000
        order_inserts: true
        order_updates: true
        jdbc:
          time_zone: Asia/Seoul

  logging:
    level:
      org.springdoc: DEBUG
      org.hibernate.SQL: DEBUG
      org.springframework.security: DEBUG

  security:
    user:
      name: admin
      password: admin
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope:
            - user:email
            - read:user
            redirect-uri: ${GITHUB_REDIRECT_URI}
#          google:
#            client-id: your-google-client-id
#            client-secret: your-google-client-secret
#            scope: profile, email
#          kakao:
#            client-id: your-kakao-client-id
#            client-secret: your-kakao-client-secret
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: profile_nickname, account_email
#            client-name: Kakao
#          naver:
#            client-id: your-naver-client-id
#            client-secret: your-naver-client-secret
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: name, email
#            client-name: Naver

  management:
    endpoints:
      web:
        exposure:
          include: health, info
    endpoint:
      health:
        show-details: always
    server:
      port: 8080
    security:
      enabled: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  paths-to-match: /**
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

