spring:
  datasource:
    url: jdbc:mysql://${DEV_DB_HOST}:${DB_PORT:3306}/${DEV_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
