spring:
  datasource:
    url: jdbc:mysql://${PROD_DB_HOST}:${DB_PORT:3306}/${PROD_DB_NAME}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      default_batch_fetch_size: 1000
      jdbc:
        time_zone: Asia/Seoul
    defer-datasource-initialization: true
    show-sql: false
    open-in-view: false

management:
  server:
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true

server:
  forward-headers-strategy: native
  address: 0.0.0.0
  port: 8080
  ssl:
    enabled: false