spring:
  application:
    name: I-Contact

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:i_contact_local}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
        order_inserts: true
        order_updates: true
        jdbc:
          time_zone: Asia/Seoul

  logging:
    level:
      org.hibernate.SQL: debug

  security:
    oauth2:
      client:
        registration:
#          google:
#            client-id: your-google-client-id
#            client-secret: your-google-client-secret
#            scope: profile, email
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: user:email
#          kakao:
#            client-id: your-kakao-client-id
#            client-secret: your-kakao-client-secret
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: profile_nickname, account_email
#            client-name: Kakao
#          naver:
#            client-id: your-naver-client-id
#            client-secret: your-naver-client-secret
#            client-authentication-method: POST
#            authorization-grant-type: authorization_code
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            scope: name, email
#            client-name: Naver
