name: CD - Build & Deploy to EC2

on:
  push:
    branches:
      - main
      - dev
    workflow_run:
      workflows: [ "CI - Build & Test" ]
      types:
        - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          IFS=',' read -r -a IPS <<< "${{ secrets.EC2_PUBLIC_IP }}"
          for IP in "${IPS[@]}"; do
            ssh-keyscan -H "$IP" >> ~/.ssh/known_hosts
          done

      - name: Deploy to EC2
        run: |
          IFS=',' read -r -a IPS <<< "${{ secrets.EC2_PUBLIC_IP }}"
          for IP in "${IPS[@]}"; do
            ssh -o StrictHostKeyChecking=no ubuntu@"$IP" <<EOF
cd /home/ubuntu/your-project-folder
git pull origin main || echo "Git pull failed, check if branch exists"
docker-compose down || echo "No running containers"
docker-compose up -d --build
EOF
          done
